Set `czi_filename` in the CziFile constructor
AllenCellModeling/aicspylibczi pull request #41
Opened 2020-04-29 18:53 UTC by ChiliJohnson

This sets the `czi_filename` property in the `CziFile` constructor using the corresponding argument, where previously it was always set to `None`. As far as I can tell, this `czi_filename` property isn't set by any side effects elsewhere, so I feel like it should either not exist or get set to a reasonable value.

Unrelated to this change, but seeing as this argument can be more than just a filename (e.g. a buffer) should this argument/property be renamed?

2020-04-29 21:38 UTC, JacksonMaxfield commented
> Unrelated to this change, but seeing as this argument can be more than just a filename (e.g. a buffer) should this argument/property be renamed?

Probably. @heeler something like `self.filelike_pointer`? I am trying to solve this with the `aicsimageio` read from S3 / GCS / Azure and etc. so going to have to make similar changes over on that repo too. Should standardize.

2020-04-30 18:48 UTC, heeler commented
Yup good catch. When I was implementing this, getting file pointers to cross from python to C++ was challenging. The czi_filename member variable was added then until I got the file pointer crossing to work and rather than deleting it I set it to none. I'll chat with Jackson to figure out a unified approach for our readers (aicsimageio).

2020-10-08 16:14 UTC, heeler requested changes
Thanks for pointing this out. I apologize for not addressing your PR sooner. It fell through the cracks and there was a concern that I might have to reverse some work that passed the byte-stream across from Python to C++. 
If you could modify the PR I'll merge it. Thanks for contributing!

2020-10-08 16:14 UTC, heeler commented on aicspylibczi/CziFile.py
> +        self.czi_filename = czi_filename
Could you modify the PR to delete the variable `self.czi_filename` meaning just remove this line? Then I'll merge it.

2020-10-13 19:46 UTC, ChiliJohnson commented
No worries! Just fully removed that line

2020-10-13 19:49 UTC, heeler approved these changes

2020-10-13 19:50 UTC, merged